; Indentation untuk cfscript (grammar tidak menyediakan indents.scm upstream)

(statement_block "{" @indent)
(statement_block "}" @dedent)
(switch_body "{" @indent)
(switch_body "}" @dedent)
(object "{" @indent)
(object "}" @dedent)
(object_pattern "{" @indent)
(object_pattern "}" @dedent)
(formal_parameters "(" @indent)
(formal_parameters ")" @dedent)
(arguments "(" @indent)
(arguments ")" @dedent)
(parenthesized_expression "(" @indent)
(parenthesized_expression ")" @dedent)
(array "[" @indent)
(array "]" @dedent)
(array_pattern "[" @indent)
(array_pattern "]" @dedent)
