-- activate config spesific languages
pcode.lang = {
	angular = false,
	cpp = false,
	deno = false,
	golang = false,
	java = false,
	--[[ 	java2 = false,
	java3 = false,
	java4 = false, ]]
	javascript = false,
	kotlin = false,
	markdown = false,
	php = false,
	prisma = false,
	python = false,
	rust = false,
	sql = false,
	tailwind = false,
}
-- activate config extras
pcode.extras = {
	autosave = false,
	bigfiles = false,
	bufferline = true,
	cheatsheet = false,
	codeium = false,
	codeiumnvim = false,
	colorizer = true,
	dap = false,
	deviconcolor = false,
	dressing = true,
	fidget = false,
	hilightcolor = false,
	illuminate = false,
	indentscupe = false,
	liveserver = false,
	lspprogress = false,
	minianimate = false,
	navic = true,
	neocodeium = true,
	neoscroll = false,
	nvimmenu = false,
	nvimufo = false,
	rainbowdelimiters = true,
	refactoring = false,
	rest = false,
	scrollview = false,
	showkeys = false,
	smartsplit = false,
	startuptime = false,
	telescopediff = false,
	telescopetreesiterinfo = false,
	tinydignostic = false,
	transparent = true,
	treesittercontex = false,
	verticalcolumn = false,
	visualmulti = true,
	yanky = true,
	zenmode = false,
}
-- activate config themes
-- evatheme = "Eva-Dark",
-- evatheme = "Eva-Dark-Italic",
-- evatheme = "Eva-Dark-Bold",
-- evatheme = "Eva-Light",
-- dracula = "dracula",
-- dracula = "dracula-soft",
-- onedarkpro = "onedark",
-- onedarkpro = "onedark_vivid",
-- onedarkpro = "onedark_dark",
-- jetbrains = "darcula-dark",
-- sublimetext = "juliana",
-- tokyonight = "tokyonight-night",
-- tokyonight = "tokyonight-storm",
-- tokyonight = "tokyonight-day",
-- tokyonight = "tokyonight-moon",
-- catppuccin = "catppuccin",
-- catppuccin = "catppuccin-latte",
-- catppuccin = "catppuccin-frappe",
-- catppuccin = "catppuccin-macchiato",
-- catppuccin = "catppuccin-macchiato",
-- gruvbox = "gruvbox",
-- github = "github_dark_dimmed",

pcode.themes = {
  evatheme = "Eva-Dark"
}
-- activate config transparent_bg
-- pcode.transparent=false
pcode.localcode = false
pcode.snippets_path = vim.fn.stdpath("config") .. "/mysnippets"
pcode.use_nvimtree = true
pcode.nvimtree_float = false
